cleanup

diff --git a/debian/wireguard.client/wireguard-client.yml b/debian/wireguard.client/wireguard-client.yml
--- a/debian/wireguard.client/wireguard-client.yml
+++ b/debian/wireguard.client/wireguard-client.yml
@@ -89,23 +89,20 @@
           wgdnsip=$(grep "^DNS" $wireguard_config | cut -d= -f2 | cut -d, -f1)
 
           # look for known issue (happens in some cases afer machine reboot)
-          nmcli connection | grep -q " wg-client" && if ! ping -c1 $wgdnsip >$g_tmp/ping_out 2>&1
-          then
-            if grep -q 'ping: sendmsg: Destination address required' $g_tmp/ping_out
-            then
-              g_echo "Known routing or whatever failure when network isn't up fast enough - "
-              nmcli connection down wg-client
-              nmcli connection up wg-client
-              systemctl restart tor.service
-            fi
-            rm -f $g_tmp/ping_out
-          fi
-
-          [ -s $wireguard_config ] || exit 0
+          #nmcli connection | grep -q " wg-client" && if ! ping -c1 $wgdnsip >$g_tmp/ping_out 2>&1
+          #then
+          #  if grep -q 'ping: sendmsg: Destination address required' $g_tmp/ping_out
+          #  then
+          #    g_echo "Known routing or whatever failure when network isn't up fast enough - "
+          #    nmcli connection down wg-client
+          #    nmcli connection up wg-client
+          #    systemctl restart tor.service
+          #  fi
+          #  rm -f $g_tmp/ping_out
+          #fi
 
           if ping -c3 $wgdnsip >$g_tmp/ping_out 2>&1
           then
-            cat $g_tmp/ping_out
             g_echo "wireguard connection OK"
             exit 0
           fi
@@ -116,15 +113,6 @@
           if ! host -W5 $wghost
           then
             g_echo_warn "DNS for $wghost not working"
-            #g_check_fix_dns_stack
-            # maybe vpn is blocking dns - if active remove
-            #if nmcli connection | grep -q " wg-client"
-            #then
-            #  g_echo_warn "removing wg-client - maybe its blocking DNS/Internet access"
-            #  nmcli connection down wg-client
-            #  nmcli connection delete wg-client
-            #  g_check_fix_dns_stack
-            #fi
             exit 1
           fi
 
